name: generate ascii

on: 
    push

jobs:
#   ascii_job:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repo
#       uses: actions/checkout@v4
    
#     - name: List Repo Files
#       run: ls -ltra
#       # Added
#     - name: Exectuing shell script
#       run: |
#         chmod +x ascii-script.sh
#         ./ascii-script.sh
    deploy_job_1:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message
              run: echo "hi"
            
            - name: "Install cowsay program"
              run: sudo apt-get install cowsay -y
        
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover , I am a dragon " >> dragon.txt  
            
            - name: Upload Dragon textfile
              uses: actions/upload-artifact@v6
              with:
                name: my-artifact
                path: path/to/artifact/world.txt

    deploy_job_2:
        needs: deploy_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon File
          uses: actions/download-artifact@v6
          with:
            name: dragon.txt
        
        - name: Text file Exists
          run: grep -i "dragon" dragon.txt      

    deploy_job_3:
        needs: deploy_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon
          uses: actions/download-artifact@v6
          with:
            name: dragon.txt

        - name: Read File
          run: cat dragon.txt
        
        - name: Deploy
          run: echo Deploying... .. . 