name: Exploring variables and Secrets

on:
    push
env: 
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: nikhireddy
    IMAGE_NAME: github-actions-nginx

jobs:
    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: docker build -t docker.io/dockerUsername/imageName:latest

    #     - name: docker login
    #       run: docker login --username=nikhireddy --password=Nikhi@999.com
        
    #     - name: Docker Publish
    #       run: docker push docker.io/dockerUsername/imageName:latest

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker run
    #       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest


###########################3 environment variables at step level #################################################

    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker build
    #       env: 
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: nikhireddy
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    #     - name: Docker login
    #       env: 
    #         DOCKER_PASSWORD: Nikhi@999.com
    #         DOCKER_USERNAME: nikhireddy
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
          
    #     - name: Docker publish
    #       env: 
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: nikhireddy
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Run
    #       env: 
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: nikhireddy
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

# ######################### Environment variables at job level ##########################################################
# env should be before jobs
# env: 
#     CONTAINER_REGISTRY: docker.io
#     DOCKER_USERNAME: nikhireddy
#     IMAGE_NAME: github-actions-nginx

    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: docker login
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        
        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest